apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-fastapi-app
  template:
    metadata:
      labels:
        app: my-fastapi-app
    spec:
      containers:
        - name: my-fastapi-app
          image: harnilshah/my-fastapi-app:latest
          ports:
            - containerPort: 8000
